Update app.py
BUMETCS673/project-team-5 pull request #4
Opened 2023-09-24 12:40 UTC by lazpz61BU

Using this branch to update Main with folders and files from Main after pulling from Main and branching out to merge changes properly.

2023-09-25 02:41 UTC, smathis122 approved these changes

2023-09-25 17:21 UTC, casejade37 requested changes
The only thing is .gitignore. Let me know when complete so I can approve the change

2023-09-25 17:21 UTC, casejade37 commented on node_modules/.bin/loose-envify
You should add the whole node_modules package into .gitignore like below

# dependencies
/node_modules

2023-09-25 17:21 UTC, casejade37 commented on node_modules/.bin/loose-envify
OK I checked on your branch and it turns out that you had this in your .gitignore but your node_modules were installed incorrectly outside of our code folder. Can you update this? Otherwise you need to deal with merge conflicts anyway.

2023-09-26 00:46 UTC, casejade37 approved these changes

2023-09-26 01:04 UTC, merged